"""Add users table

Revision ID: 08dece376c5d
Revises: ecf2304f9f51
Create Date: 2025-03-19 01:37:12.353689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08dece376c5d'
down_revision: Union[str, None] = 'ecf2304f9f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_card_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('main_image', sa.String(), nullable=True),
    sa.Column('side_image', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PRIVATE', 'SUBSCRIBERS', 'PUBLIC', name='reportstatusenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_card_content_id'), 'report_card_content', ['id'], unique=False)
    op.create_table('user_report_card',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report_card_content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_report_card')
    op.drop_index(op.f('ix_report_card_content_id'), table_name='report_card_content')
    op.drop_table('report_card_content')
    # ### end Alembic commands ###
