"""Initial database structure

Revision ID: 1c5fc92ac64e
Revises: c5f02f993732
Create Date: 2025-03-20 10:13:23.167166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5fc92ac64e'
down_revision: Union[str, None] = 'c5f02f993732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('likes_status', sa.Enum('PUBLIC', 'PRIVATE', 'FRIENDS_ONLY', name='visibility_option'), nullable=False))
    op.add_column('reports', sa.Column('comment_status', sa.Enum('PUBLIC', 'PRIVATE', 'FRIENDS_ONLY', name='visibility_option'), nullable=False))
    op.add_column('reports', sa.Column('addit_file_status', sa.Enum('PUBLIC', 'PRIVATE', 'FRIENDS_ONLY', name='visibility_option'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'addit_file_status')
    op.drop_column('reports', 'comment_status')
    op.drop_column('reports', 'likes_status')
    # ### end Alembic commands ###
