"""Initial database structure

Revision ID: 4386c04e916c
Revises: e9406d27403a
Create Date: 2025-03-20 16:13:05.569378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4386c04e916c'
down_revision: Union[str, None] = 'e9406d27403a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('attempts', sa.Integer(), nullable=True))
    op.alter_column('password_reset_tokens', 'reset_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_reset_tokens', 'reset_code',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.drop_column('password_reset_tokens', 'attempts')
    # ### end Alembic commands ###
