"""Initial database structure

Revision ID: 48d44d73bc05
Revises: f5d8ed7f1e9c
Create Date: 2025-03-20 10:36:22.554660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d44d73bc05'
down_revision: Union[str, None] = 'f5d8ed7f1e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_report_card', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_report_card', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_report_card', type_='foreignkey')
    op.drop_constraint(None, 'user_report_card', type_='foreignkey')
    # ### end Alembic commands ###
