"""Initial database structure

Revision ID: 4dd0de9d7b7e
Revises: cbe48455cf2a
Create Date: 2025-03-20 01:21:20.883577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dd0de9d7b7e'
down_revision: Union[str, None] = 'cbe48455cf2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_card_content', sa.Column('report_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'report_card_content', ['report_id'])
    op.create_foreign_key(None, 'report_card_content', 'reports', ['report_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report_card_content', type_='foreignkey')
    op.drop_constraint(None, 'report_card_content', type_='unique')
    op.drop_column('report_card_content', 'report_id')
    # ### end Alembic commands ###
