"""Change status to string

Revision ID: 4e832d79bdef
Revises: 1076ff98888a
Create Date: 2025-03-19 23:46:33.447402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e832d79bdef'
down_revision: Union[str, None] = '1076ff98888a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_card_content', 'status',
               existing_type=postgresql.ENUM('draft', 'private', 'public', 'friends_only', name='report_status'),
               type_=sa.String(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_card_content', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('draft', 'private', 'public', 'friends_only', name='report_status'),
               nullable=True)
    # ### end Alembic commands ###
