"""Initial database structure

Revision ID: c20776ba6030
Revises: f68818ab71c1
Create Date: 2025-03-20 01:31:17.248068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20776ba6030'
down_revision: Union[str, None] = 'f68818ab71c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('report_card_content_report_id_key', 'report_card_content', type_='unique')
    op.drop_constraint('report_card_content_report_id_fkey', 'report_card_content', type_='foreignkey')
    op.drop_column('report_card_content', 'report_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_card_content', sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('report_card_content_report_id_fkey', 'report_card_content', 'reports', ['report_id'], ['id'])
    op.create_unique_constraint('report_card_content_report_id_key', 'report_card_content', ['report_id'])
    # ### end Alembic commands ###
