"""Initial database structure

Revision ID: f2b3351e9b9b
Revises: 10bee8fb9177
Create Date: 2025-03-20 10:06:19.668933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2b3351e9b9b'
down_revision: Union[str, None] = '10bee8fb9177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_report_card_status', table_name='report_card_content')
    op.drop_index('idx_report_card_user', table_name='report_card_content')
    op.drop_index('ix_report_card_content_id', table_name='report_card_content')
    op.drop_index('ix_report_card_content_user_id', table_name='report_card_content')
    op.drop_table('report_card_content')
    op.add_column('reports', sa.Column('description', sa.String(length=1000), nullable=False))
    op.add_column('reports', sa.Column('side_image', sa.String(length=512), nullable=True))
    op.add_column('reports', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('reports', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('reports', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('likes', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('comments_count', sa.Integer(), nullable=False))
    op.drop_constraint('reports_report_card_id_key', 'reports', type_='unique')
    op.create_index('idx_report_user', 'reports', ['user_id'], unique=False)
    op.drop_constraint('reports_report_card_id_fkey', 'reports', type_='foreignkey')
    op.drop_column('reports', 'report_card_id')
    op.drop_constraint('user_report_card_report_id_fkey', 'user_report_card', type_='foreignkey')
    op.create_foreign_key(None, 'user_report_card', 'reports', ['report_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_report_card', type_='foreignkey')
    op.create_foreign_key('user_report_card_report_id_fkey', 'user_report_card', 'report_card_content', ['report_id'], ['id'])
    op.add_column('reports', sa.Column('report_card_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('reports_report_card_id_fkey', 'reports', 'report_card_content', ['report_card_id'], ['id'])
    op.drop_index('idx_report_user', table_name='reports')
    op.create_unique_constraint('reports_report_card_id_key', 'reports', ['report_card_id'])
    op.drop_column('reports', 'comments_count')
    op.drop_column('reports', 'likes')
    op.drop_column('reports', 'duration')
    op.drop_column('reports', 'end_date')
    op.drop_column('reports', 'start_date')
    op.drop_column('reports', 'side_image')
    op.drop_column('reports', 'description')
    op.create_table('report_card_content',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('main_image', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('side_image', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PRIVATE', 'PUBLIC', 'FRIENDS_ONLY', name='report_status'), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comments_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='check_dates'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='report_card_content_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='report_card_content_pkey')
    )
    op.create_index('ix_report_card_content_user_id', 'report_card_content', ['user_id'], unique=False)
    op.create_index('ix_report_card_content_id', 'report_card_content', ['id'], unique=False)
    op.create_index('idx_report_card_user', 'report_card_content', ['user_id'], unique=False)
    op.create_index('idx_report_card_status', 'report_card_content', ['status'], unique=False)
    # ### end Alembic commands ###
