"""Initial database structure

Revision ID: f5d8ed7f1e9c
Revises: 25edfe44a02a
Create Date: 2025-03-20 10:28:57.426927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d8ed7f1e9c'
down_revision: Union[str, None] = '25edfe44a02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('title', sa.String(length=255), nullable=False))
    op.drop_column('reports', 'destination')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('destination', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('reports', 'title')
    # ### end Alembic commands ###
